baseURL = "https://blog-b11ed.firebaseapp.com/"
languageCode = "en-us"
title = "Blog | Stephanie Wilkinson"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-96996170-2"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/stephanieblack"
  instagram = "http://instagram.com/stephanie.pix"
  youtube = ""
  github = "https://github.com/stephaniewilkinson"
  linkedin = "http://linkedin.com/in/stephanieawilkinson"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/pointing.gif"
  images = ["site-feature-image.jpg"]
